version: "2"
services:
  radar:
    build: ./radar/
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      options:
        max-size: 1m
  pitherm:
    build: ./pitherm/
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "/sys/bus/w1/:/sys/bus/w1/"
      - type: bind
        source: "/sys/class/gpio"
        target: "/sys/class/gpio"
        read_only: false
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      options:
        max-size: 1m
  web:
    build: ./web/
    restart: always
    env_file: .env
    network_mode: host
    ports:
      - "80:80"
    depends_on:
      - radar
      - pitherm
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      options:
        max-size: 1m
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
    env_file: .env
    logging:
      options:
        max-size: 1m

volumes:
  web:
