version: '2'
services:
  db:
    build: ./db/
    restart: always
    env_file: .env
    volumes:
      - 'db:/var/lib/mysql'
  radar:
    build: ./radar/
    restart: always
    env_file: .env
    depends_on:
      - db
    external_links:
      - db:db
  pitherm:
    build: ./pitherm/
    restart: always
    env_file: .env
    volumes:
      - "/sys/bus/w1/:/sys/bus/w1/"
    devices:
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    depends_on:
      - db
    external_links:
      - db:db
  web:
    build: ./web/
    restart: always
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db
      - radar
      - pitherm
    external_links:
      - db:db

volumes:
  db:
